---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/webapp"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
      # group all dev dependencies together regardless of versions
      dev-dependencies:
        patterns:
          - "@babel*"
          - "@types*"
          - "babel*"
          - "*vite*"
          - "*loader*"
      # group all other minor and patches
      minor-and-patches:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

