version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Docker/Dockerfile.local
      target: base
    volumes:
      - ./server/src:/home/server/app/src
      - ./server/nodemon.json:/home/server/app/nodemon.json
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev
