name: Server CI

on:
  workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install package
        run: |
          npm install
          cd server
          npm install
      - name: Run lint
        run: |
          cd server
          npm run lint
